public class Table {
    public static final Cell[][] TABLE = new Cell[][] {
    //                      FACTORIAL                        PLUS                       MINUS                        STAR                        FUNC                      NUMBER                    OBRACKET                    CBRACKET                           $                       start                           t                           f
        {                        null,                       null,  new Cell(Action.SHIFT, 7),                       null,  new Cell(Action.SHIFT, 4),  new Cell(Action.SHIFT, 2),  new Cell(Action.SHIFT, 1),                       null,                       null,  new Cell(Action.SHIFT, 6),  new Cell(Action.SHIFT, 3),  new Cell(Action.SHIFT, 5) },
        {                        null,                       null,  new Cell(Action.SHIFT, 7),                       null,  new Cell(Action.SHIFT, 4),  new Cell(Action.SHIFT, 2),  new Cell(Action.SHIFT, 1),                       null,                       null,  new Cell(Action.SHIFT, 8),  new Cell(Action.SHIFT, 3),  new Cell(Action.SHIFT, 5) },
        {  new Cell(Action.REDUCE, 6), new Cell(Action.REDUCE, 6), new Cell(Action.REDUCE, 6), new Cell(Action.REDUCE, 6),                       null,                       null,                       null, new Cell(Action.REDUCE, 6), new Cell(Action.REDUCE, 6),                       null,                       null,                       null },
        {                        null, new Cell(Action.REDUCE, 1), new Cell(Action.REDUCE, 1),  new Cell(Action.SHIFT, 9),                       null,                       null,                       null, new Cell(Action.REDUCE, 1), new Cell(Action.REDUCE, 1),                       null,                       null,                       null },
        {                        null,                       null,                       null,                       null,                       null,                       null, new Cell(Action.SHIFT, 11),                       null,                       null,                       null,                       null,                       null },
        {  new Cell(Action.SHIFT, 13), new Cell(Action.REDUCE, 4), new Cell(Action.REDUCE, 4), new Cell(Action.REDUCE, 4),                       null,                       null,                       null, new Cell(Action.REDUCE, 4), new Cell(Action.REDUCE, 4),                       null,                       null,                       null },
        {                        null, new Cell(Action.SHIFT, 14), new Cell(Action.SHIFT, 15),                       null,                       null,                       null,                       null,                       null, new Cell(Action.REDUCE, 0),                       null,                       null,                       null },
        {                        null,                       null,  new Cell(Action.SHIFT, 7),                       null,  new Cell(Action.SHIFT, 4),  new Cell(Action.SHIFT, 2),  new Cell(Action.SHIFT, 1),                       null,                       null,                       null,                       null, new Cell(Action.SHIFT, 18) },
        {                        null, new Cell(Action.SHIFT, 14), new Cell(Action.SHIFT, 15),                       null,                       null,                       null,                       null, new Cell(Action.SHIFT, 20),                       null,                       null,                       null,                       null },
        {                        null,                       null,  new Cell(Action.SHIFT, 7),                       null,  new Cell(Action.SHIFT, 4),  new Cell(Action.SHIFT, 2),  new Cell(Action.SHIFT, 1),                       null,                       null,                       null,                       null, new Cell(Action.SHIFT, 10) },
        {  new Cell(Action.SHIFT, 13), new Cell(Action.REDUCE, 5), new Cell(Action.REDUCE, 5), new Cell(Action.REDUCE, 5),                       null,                       null,                       null, new Cell(Action.REDUCE, 5), new Cell(Action.REDUCE, 5),                       null,                       null,                       null },
        {                        null,                       null,  new Cell(Action.SHIFT, 7),                       null,  new Cell(Action.SHIFT, 4),  new Cell(Action.SHIFT, 2),  new Cell(Action.SHIFT, 1),                       null,                       null, new Cell(Action.SHIFT, 12),  new Cell(Action.SHIFT, 3),  new Cell(Action.SHIFT, 5) },
        {                        null, new Cell(Action.SHIFT, 14), new Cell(Action.SHIFT, 15),                       null,                       null,                       null,                       null, new Cell(Action.SHIFT, 16),                       null,                       null,                       null,                       null },
        { new Cell(Action.REDUCE, 10),new Cell(Action.REDUCE, 10),new Cell(Action.REDUCE, 10),new Cell(Action.REDUCE, 10),                       null,                       null,                       null,new Cell(Action.REDUCE, 10),new Cell(Action.REDUCE, 10),                       null,                       null,                       null },
        {                        null,                       null,  new Cell(Action.SHIFT, 7),                       null,  new Cell(Action.SHIFT, 4),  new Cell(Action.SHIFT, 2),  new Cell(Action.SHIFT, 1),                       null,                       null,                       null, new Cell(Action.SHIFT, 17),  new Cell(Action.SHIFT, 5) },
        {                        null,                       null,  new Cell(Action.SHIFT, 7),                       null,  new Cell(Action.SHIFT, 4),  new Cell(Action.SHIFT, 2),  new Cell(Action.SHIFT, 1),                       null,                       null,                       null, new Cell(Action.SHIFT, 19),  new Cell(Action.SHIFT, 5) },
        {  new Cell(Action.REDUCE, 9), new Cell(Action.REDUCE, 9), new Cell(Action.REDUCE, 9), new Cell(Action.REDUCE, 9),                       null,                       null,                       null, new Cell(Action.REDUCE, 9), new Cell(Action.REDUCE, 9),                       null,                       null,                       null },
        {                        null, new Cell(Action.REDUCE, 2), new Cell(Action.REDUCE, 2),  new Cell(Action.SHIFT, 9),                       null,                       null,                       null, new Cell(Action.REDUCE, 2), new Cell(Action.REDUCE, 2),                       null,                       null,                       null },
        {  new Cell(Action.SHIFT, 13), new Cell(Action.REDUCE, 8), new Cell(Action.REDUCE, 8), new Cell(Action.REDUCE, 8),                       null,                       null,                       null, new Cell(Action.REDUCE, 8), new Cell(Action.REDUCE, 8),                       null,                       null,                       null },
        {                        null, new Cell(Action.REDUCE, 3), new Cell(Action.REDUCE, 3),  new Cell(Action.SHIFT, 9),                       null,                       null,                       null, new Cell(Action.REDUCE, 3), new Cell(Action.REDUCE, 3),                       null,                       null,                       null },
        {  new Cell(Action.REDUCE, 7), new Cell(Action.REDUCE, 7), new Cell(Action.REDUCE, 7), new Cell(Action.REDUCE, 7),                       null,                       null,                       null, new Cell(Action.REDUCE, 7), new Cell(Action.REDUCE, 7),                       null,                       null,                       null }
    
    };
    public enum Action {
            SHIFT, REDUCE
    }
    public record Cell(Action action, int number) {
    }

}